### ISSUE TITLE
yasm error "invalid size for operand 1" when building libass

### ISSUE THREAD

**Issue by scjhan** [ShiftMediaProject/libass#2]
yasm error "invalid size for operand 1" when building libass

## Context
I got this error "invalid size for operand 1" when building libass sub project, I'm not familiar with assembly language, could you help me?
```
1>  ..\libass\x86\blend_bitmaps.asm
1>D:\github\ffmpeg_smp\src\libass\libass\x86\blend_bitmaps.asm(94): error : invalid size for operand 1
```

**Comment by Sibras** [comment]
Youll need to provide alot more information:
What configuration|architecture are you building with?
What version of visual studio?
The provided libass project has been tested and the above error can not be reproduced so there is clearly something different with you setup/use case.
