### ISSUE TITLE
Update to latest libass builds

### ISSUE THREAD

**Issue by adipose** [ShiftMediaProject/libass#3]
Could you import the latest source?

**Comment by Sibras** [comment]
libass is already at the latest stable version 0.14.0. This repo only tracks stable releases so until a new release is marked stable by upstream libass then this repo is already at the latest.

**Comment by Sibras** [comment]
By the way, I generally update to the latest release as quick as I can so if there is a feature in upstream master that you want then if you get them to tag a release ill update then.

**Comment by adipose** [comment]
I understand your reasoning.  Since libass hasn't had a release in so long, we were considering using later sources.
